PR ontram-pkg
LucasKook/ontram-pkg pull request #1
Opened 2021-11-06 10:03 UTC by AGoetschi

2021-11-08 07:50 UTC, LucasKookUZH commented on R/fit_ontram.R
> +            save_model_ontram(model, filename = paste0(filepath, "best_model"))
Add file ending `.h5` to `"best_model"`.

2021-11-08 07:51 UTC, LucasKookUZH commented on R/fit_ontram.R
> +      if (is.null(filepath) || !dir.exists(filepath)) stop("`filepath` missing or does not exist.")
Maybe instead of stopping, `dir.create()` the missing directory?

2021-11-08 07:54 UTC, LucasKookUZH commented on R/methods.R
> +    runif(1)
This `runif(1)` call looks a bit weird. I'd probably assign it to a variable? Is it just to get the `".Random.seed"` initialized?

2021-11-08 08:05 UTC, LucasKookUZH requested changes
Thanks for the PR! There are some minor comments in the review, please address.

2021-11-08 08:05 UTC, LucasKook commented on R/methods.R
> +      tmp[[i]] <- ordered(ret[i, ])
Add the correct levels to the ordered outcome using `levels = ...`

2021-11-08 08:05 UTC, LucasKook commented on R/save-load_ontram.R
> +                           optimizer = tf$keras$optimizers$Adam(learning_rate = 0.001),
The learning rate should probably be written and read as well. The `distr` argument can remain `tf$sigmoid` for the time being.

2021-11-08 08:05 UTC, LucasKook commented on README.md
> +remotes::install_github("AGoetschi/ontram-pkg")
Please revert change.

2021-11-08 08:05 UTC, LucasKookUZH commented on R/save-load_history.R
> +#' @rdname save_history_ontram
Remove/change `@rdname` field.

2021-11-08 08:05 UTC, LucasKook commented on R/save-load_ontram.R
> +#' @rdname save_model_ontram
Change/remove `@rdname` field.

2021-11-08 08:05 UTC, LucasKook commented on R/fit_ontram.R
> +      if (is.null(filepath) || !dir.exists(filepath)) stop("`filepath` missing or does not exist.")
Maybe instead of stopping, `dir.create()` the missing directory?

2021-11-10 14:34 UTC, LucasKookUZH approved these changes
Thanks!

2021-11-10 14:34 UTC, LucasKookUZH commented on R/save-load_ontram.R
> +    class(ret) <- append("ontram_rv", class(ret))
`append()` adds to the end of a vector, however `"ontram_rv"` should be the first class.
```r
class(ret) <- c("ontram_rv", class(ret))
```
will fix this.

2021-11-10 14:34 UTC, merged